import type { CompanyProfile } from "@/lib/types";

// 3 家虚构演示企业，数据均为人工设定，用于展示匹配逻辑
export const demoCompanies: (CompanyProfile & { demoId: string; tagline: string })[] = [
  {
    demoId: "demo-startup",
    tagline: "5人 · 大学生初创 · 农村电商",
    companyName: "丽水山果电子商务有限公司（演示）",
    registeredInLishui: true,
    industry: "农村电子商务",
    employeeCount: 5,
    insuredCount: 4,
    companySize: "micro",
    unemploymentInsuranceMonths: 8,
    lastYearLayoffRate: 0,
    isSeriousDishonest: false,
    recentGradCount: 2,
    unemployedYouthCount: 0,
    contractOneYear: true,
    wageBelowAverage: true,
    lastYearUnemploymentTax: 0,
    isInternshipBase: false,
    internCount: 0,
    localMinWage: 2010,
    founderType: "毕业10年内高校毕业生",
    isFirstVenture: true,
    operatingMonths: 10,
    jobsCreated: 4,
    socialInsuranceOneYear: false,
    ruralEcommerce: true,
    hasRnD: false,
    rndAmount: 0,
    rndGrowth: null,
    rndRatio: null,
    ipCount: 0,
    techSMEStatus: "none",
    isSpecialized: false,
  },
  {
    demoId: "demo-tech",
    tagline: "30人 · 科技型成长企业 · 有研发投入",
    companyName: "丽水智控科技有限公司（演示）",
    registeredInLishui: true,
    industry: "智能制造与软件信息",
    employeeCount: 30,
    insuredCount: 29,
    companySize: "small",
    unemploymentInsuranceMonths: 36,
    lastYearLayoffRate: 0,
    isSeriousDishonest: false,
    recentGradCount: 2,
    unemployedYouthCount: 0,
    contractOneYear: true,
    wageBelowAverage: false,
    lastYearUnemploymentTax: 24000,
    isInternshipBase: false,
    internCount: 0,
    localMinWage: 2010,
    founderType: "普通经营者",
    isFirstVenture: false,
    operatingMonths: 60,
    jobsCreated: 0,
    socialInsuranceOneYear: false,
    ruralEcommerce: false,
    hasRnD: true,
    rndAmount: 120,
    rndGrowth: 20,
    rndRatio: 8,
    ipCount: 6,
    techSMEStatus: "none",
    isSpecialized: false,
  },
  {
    demoId: "demo-trade",
    tagline: "15人 · 传统商贸 · 经营稳定",
    companyName: "丽水万家商贸有限公司（演示）",
    registeredInLishui: true,
    industry: "批发零售",
    employeeCount: 15,
    insuredCount: 14,
    companySize: "small",
    unemploymentInsuranceMonths: 48,
    lastYearLayoffRate: 0,
    isSeriousDishonest: false,
    recentGradCount: 0,
    unemployedYouthCount: 0,
    contractOneYear: true,
    wageBelowAverage: null,
    lastYearUnemploymentTax: 11000,
    isInternshipBase: false,
    internCount: 0,
    localMinWage: 2010,
    founderType: "普通经营者",
    isFirstVenture: false,
    operatingMonths: 80,
    jobsCreated: 0,
    socialInsuranceOneYear: false,
    ruralEcommerce: false,
    hasRnD: false,
    rndAmount: 0,
    rndGrowth: null,
    rndRatio: null,
    ipCount: 0,
    techSMEStatus: "none",
    isSpecialized: false,
  },
];

export function getDemoCompany(demoId: string): CompanyProfile | undefined {
  return demoCompanies.find((c) => c.demoId === demoId);
}
